"""add emote_set_owner_id to voting_events

Revision ID: 07af03576894
Revises: a6c87ace9e74
Create Date: 2025-11-23 22:22:05.905464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07af03576894'
down_revision: Union[str, Sequence[str], None] = 'a6c87ace9e74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['twitch_user_id'])
    op.add_column('voting_events', sa.Column('emote_set_owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'voting_events', 'users', ['emote_set_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voting_events', type_='foreignkey')
    op.drop_column('voting_events', 'emote_set_owner_id')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
