"""Create initial tables

Revision ID: 0abc41164cd9
Revises: 
Create Date: 2025-08-07 18:55:21.001433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abc41164cd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_username', sa.String(), nullable=False),
    sa.Column('sevenTV_id', sa.String(), nullable=False),
    sa.Column('can_create_votes_for', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('moderators', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sevenTV_id'),
    sa.UniqueConstraint('twitch_username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pending_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitch_username', sa.String(), nullable=True),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('permission_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_permissions_id'), 'pending_permissions', ['id'], unique=False)
    op.create_table('voting_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('emote_set_id', sa.String(), nullable=True),
    sa.Column('emote_set_name', sa.String(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_time_tab', sa.String(), nullable=True),
    sa.Column('permission_level', sa.String(), nullable=True),
    sa.Column('specific_users', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_events_id'), 'voting_events', ['id'], unique=False)
    op.create_table('individual_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_event_id', sa.Integer(), nullable=True),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('emote_id', sa.String(), nullable=True),
    sa.Column('vote_choice', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voting_event_id'], ['voting_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_votes_id'), 'individual_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individual_votes_id'), table_name='individual_votes')
    op.drop_table('individual_votes')
    op.drop_index(op.f('ix_voting_events_id'), table_name='voting_events')
    op.drop_table('voting_events')
    op.drop_index(op.f('ix_pending_permissions_id'), table_name='pending_permissions')
    op.drop_table('pending_permissions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
