"""Add daily visit tracking

Revision ID: 15d60d0af670
Revises: 0abc41164cd9
Create Date: 2025-08-14 19:47:22.380845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d60d0af670'
down_revision: Union[str, Sequence[str], None] = '0abc41164cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('daily_visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_visits')
    op.drop_column('users', 'last_seen_date')
    # ### end Alembic commands ###
