"""Add token fields to User

Revision ID: 1b7a1e60201e
Revises: 2021983f261b
Create Date: 2025-10-23 00:42:52.279347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7a1e60201e'
down_revision: Union[str, Sequence[str], None] = '2021983f261b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('token_scopes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_scopes')
    op.drop_column('users', 'token_expires_at')
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
