"""Add twitch_user_id to User

Revision ID: a6c87ace9e74
Revises: 1b7a1e60201e
Create Date: 2025-10-23 02:50:06.817779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c87ace9e74'
down_revision: Union[str, Sequence[str], None] = '1b7a1e60201e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Add column as nullable first
    op.add_column('users', sa.Column('twitch_user_id', sa.String(), nullable=True))
    
    # Populate existing users with a temporary value
    op.execute("UPDATE users SET twitch_user_id = 'temp_' || id::text WHERE twitch_user_id IS NULL")
    
    # Now make it NOT NULL
    op.alter_column('users', 'twitch_user_id', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'twitch_user_id')
    # ### end Alembic commands ###
